name: Git Hub Actions Demo
on: 
  push: 
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pull from repo
        uses: appleboy/ssh-action@1.2.0
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          script: |
            ls -la
      
